// Mocks generated by Mockito 5.0.16 from annotations
// in kayta_flutter/test/ServiceAgents/Login/LoginServiceAgent_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:kayta_flutter/Shared/Services/HttpService/IHttpService.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [IHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHttpService extends _i1.Mock implements _i3.IHttpService {
  MockIHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  set baseUrl(String? _baseUrl) =>
      super.noSuchMethod(Invocation.setter(#baseUrl, _baseUrl),
          returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.Response> get(String? rota,
          {Map<String, String>? headers, Duration? timeout}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #get, [rota], {#headers: headers, #timeout: timeout}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> post(String? rota,
          {dynamic body, Map<String, String>? headers, Duration? timeout}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [rota],
                  {#body: body, #headers: headers, #timeout: timeout}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
  @override
  String toString() => super.toString();
}
