name: kayta_flutter
description: Kayta para Flutter (null-safety)
version: 1.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  equatable: ^2.0.3
  package_info: ^2.0.2
  connectivity: ^3.0.6
  shared_preferences: ^2.0.9
  flutter_screenutil: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.16
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter:
